"""
Trains a REAL neural network (scikit-learn's MLPRegressor: an actual
multi-layer perceptron trained via backpropagation/Adam, with learned
weight matrices saved to disk) to predict expected mastery gain from a
resource, given the learner's current state.

WHY THIS EXISTS: the original methodology document defines the optimizer
as "max sum Gain_i" but never says what Gain_i actually IS beyond "expected
learning gain" -- every version of this project before this one used a
hand-tuned linear weighted sum (scoring.py) as a stand-in. This script
replaces that stand-in with a real, trained, nonlinear function
approximator for Gain_i, which is what a genuine hybrid recommender
(content-based ML component + knowledge-based hard constraints [the DAG]
+ personalization [the PC-BwK bandit]) actually looks like.

HOW IT'S TRAINED -- stated honestly, this is simulated, not real learner
data (no real learner data exists yet -- see RESEARCH.md): training
examples are generated from a principled pedagogical model with a real,
well-known nonlinearity: the "zone of proximal development" (Vygotsky) --
a resource whose difficulty is close to (but slightly above) the
learner's current mastery produces more learning gain than one that's
far too easy or far too hard. This nonlinear interaction between
difficulty-mismatch and current mastery is exactly the kind of pattern a
linear weighted-sum score CANNOT represent but a neural network can learn
directly from data -- this is the concrete justification for using a
neural network here rather than another hand-tuned formula.

Runs entirely locally. No API key, no external network call, ever. Once
trained, the model is a small file of learned weight matrices
(gain_predictor.joblib) loaded at server startup by predictor.py.

Usage:
    python train_gain_predictor.py
"""
from __future__ import annotations
import numpy as np
import joblib
from pathlib import Path
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

MODEL_PATH = Path(__file__).parent / "gain_predictor.joblib"
ALPHA = 0.6  # same EMA alpha as knowledge_state.py -- keep these in sync
RNG_SEED = 7


def generate_training_data(n_samples: int = 20000, seed: int = RNG_SEED):
    """
    Features (in this fixed order -- predictor.py must match):
      0: mastery_before        (0-1)
      1: resource_difficulty   (0-1)
      2: duration_ratio        (resource duration / available minutes, capped at 2.0)
      3: prereq_satisfied      (0 or 1)
      4: resource_quality      (0-1)

    Label: mastery_gain = new_mastery - mastery_before, where new_mastery
    follows the SAME EMA update rule as knowledge_state.py, and the
    underlying "performance" on the resource is generated by a
    zone-of-proximal-development model:
      ideal_difficulty = clip(mastery_before + 0.25, 0, 1)
      mismatch_penalty = |resource_difficulty - ideal_difficulty|
      base_performance = quality * (1 - mismatch_penalty) * (1.0 if prereq_satisfied else 0.45)
      base_performance also decays if duration_ratio > 1 (resource doesn't
        fit the available time well, so effective study time/focus drops)
      performance = clip(base_performance + gaussian_noise, 0, 1)
    """
    rng = np.random.default_rng(seed)
    mastery_before = rng.uniform(0, 1, n_samples)
    resource_difficulty = rng.uniform(0, 1, n_samples)
    duration_ratio = rng.uniform(0.1, 2.0, n_samples)
    prereq_satisfied = rng.integers(0, 2, n_samples)
    resource_quality = rng.uniform(0.4, 1.0, n_samples)

    ideal_difficulty = np.clip(mastery_before + 0.25, 0, 1)
    mismatch_penalty = np.abs(resource_difficulty - ideal_difficulty)
    prereq_multiplier = np.where(prereq_satisfied == 1, 1.0, 0.45)
    time_fit_multiplier = np.where(duration_ratio > 1.0, np.clip(1.0 - (duration_ratio - 1.0) * 0.5, 0.3, 1.0), 1.0)

    base_performance = resource_quality * (1 - mismatch_penalty) * prereq_multiplier * time_fit_multiplier
    noise = rng.normal(0, 0.06, n_samples)
    performance = np.clip(base_performance + noise, 0, 1)

    new_mastery = ALPHA * mastery_before + (1 - ALPHA) * performance
    mastery_gain = new_mastery - mastery_before

    X = np.column_stack([mastery_before, resource_difficulty, duration_ratio, prereq_satisfied, resource_quality])
    y = mastery_gain
    return X, y


def train():
    X, y = generate_training_data()
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=RNG_SEED)

    model = MLPRegressor(
        hidden_layer_sizes=(32, 16),
        activation="relu",
        solver="adam",
        alpha=1e-4,
        learning_rate_init=1e-3,
        max_iter=800,
        random_state=RNG_SEED,
        early_stopping=True,
        n_iter_no_change=20,
    )
    model.fit(X_train, y_train)

    pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, pred)
    r2 = r2_score(y_test, pred)
    print(f"Trained MLPRegressor: {model.n_layers_} layers, "
          f"{sum(w.size for w in model.coefs_)} weights.")
    print(f"Held-out test MAE: {mae:.4f}  R^2: {r2:.4f}")
    print(f"Converged after {model.n_iter_} iterations.")

    checks = [
        ((0.2, 0.45, 0.5, 1, 0.9), "well-matched difficulty and prereqs OK, should predict decent positive gain"),
        ((0.2, 0.95, 0.5, 1, 0.9), "way too hard for a beginner, should predict lower gain than well-matched"),
        ((0.2, 0.45, 0.5, 0, 0.9), "prereqs NOT satisfied, should predict lower gain than prereqs-OK case"),
    ]
    print("\nSanity checks:")
    for features, note in checks:
        pred_gain = model.predict([features])[0]
        print(f"  {features} -> predicted_gain={pred_gain:.4f}   [{note}]")

    joblib.dump(model, MODEL_PATH)
    print(f"\nSaved trained model to {MODEL_PATH}")


if __name__ == "__main__":
    train()
